/**
 * generated by Xtext 2.16.0
 */
package org.xtext.fLY;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declaration Object</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.fLY.DeclarationObject#getFeatures <em>Features</em>}</li>
 * </ul>
 *
 * @see org.xtext.fLY.FLYPackage#getDeclarationObject()
 * @model
 * @generated
 */
public interface DeclarationObject extends EObject
{
  /**
   * Returns the value of the '<em><b>Features</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.fLY.DeclarationFeature}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Features</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Features</em>' containment reference list.
   * @see org.xtext.fLY.FLYPackage#getDeclarationObject_Features()
   * @model containment="true"
   * @generated
   */
  EList<DeclarationFeature> getFeatures();

} // DeclarationObject
