/**
 * generated by Xtext 2.16.0
 */
package org.xtext.fLY;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>For Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.fLY.ForExpression#getIndex <em>Index</em>}</li>
 *   <li>{@link org.xtext.fLY.ForExpression#getObject <em>Object</em>}</li>
 *   <li>{@link org.xtext.fLY.ForExpression#getDelimeter <em>Delimeter</em>}</li>
 *   <li>{@link org.xtext.fLY.ForExpression#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see org.xtext.fLY.FLYPackage#getForExpression()
 * @model
 * @generated
 */
public interface ForExpression extends Expression
{
  /**
   * Returns the value of the '<em><b>Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Index</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Index</em>' containment reference.
   * @see #setIndex(ForIndex)
   * @see org.xtext.fLY.FLYPackage#getForExpression_Index()
   * @model containment="true"
   * @generated
   */
  ForIndex getIndex();

  /**
   * Sets the value of the '{@link org.xtext.fLY.ForExpression#getIndex <em>Index</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Index</em>' containment reference.
   * @see #getIndex()
   * @generated
   */
  void setIndex(ForIndex value);

  /**
   * Returns the value of the '<em><b>Object</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Object</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Object</em>' containment reference.
   * @see #setObject(ArithmeticExpression)
   * @see org.xtext.fLY.FLYPackage#getForExpression_Object()
   * @model containment="true"
   * @generated
   */
  ArithmeticExpression getObject();

  /**
   * Sets the value of the '{@link org.xtext.fLY.ForExpression#getObject <em>Object</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Object</em>' containment reference.
   * @see #getObject()
   * @generated
   */
  void setObject(ArithmeticExpression value);

  /**
   * Returns the value of the '<em><b>Delimeter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Delimeter</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Delimeter</em>' containment reference.
   * @see #setDelimeter(ForDelimeter)
   * @see org.xtext.fLY.FLYPackage#getForExpression_Delimeter()
   * @model containment="true"
   * @generated
   */
  ForDelimeter getDelimeter();

  /**
   * Sets the value of the '{@link org.xtext.fLY.ForExpression#getDelimeter <em>Delimeter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Delimeter</em>' containment reference.
   * @see #getDelimeter()
   * @generated
   */
  void setDelimeter(ForDelimeter value);

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Body</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(Expression)
   * @see org.xtext.fLY.FLYPackage#getForExpression_Body()
   * @model containment="true"
   * @generated
   */
  Expression getBody();

  /**
   * Sets the value of the '{@link org.xtext.fLY.ForExpression#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(Expression value);

} // ForExpression
