/**
 * generated by Xtext 2.16.0
 */
package org.xtext.fLY;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Index Object</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.fLY.IndexObject#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.fLY.IndexObject#getIndexes <em>Indexes</em>}</li>
 * </ul>
 *
 * @see org.xtext.fLY.FLYPackage#getIndexObject()
 * @model
 * @generated
 */
public interface IndexObject extends ObjectLiteral
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' reference.
   * @see #setName(VariableDeclaration)
   * @see org.xtext.fLY.FLYPackage#getIndexObject_Name()
   * @model
   * @generated
   */
  VariableDeclaration getName();

  /**
   * Sets the value of the '{@link org.xtext.fLY.IndexObject#getName <em>Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' reference.
   * @see #getName()
   * @generated
   */
  void setName(VariableDeclaration value);

  /**
   * Returns the value of the '<em><b>Indexes</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.fLY.SubIndex}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Indexes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Indexes</em>' containment reference list.
   * @see org.xtext.fLY.FLYPackage#getIndexObject_Indexes()
   * @model containment="true"
   * @generated
   */
  EList<SubIndex> getIndexes();

} // IndexObject
