/**
 * generated by Xtext 2.16.0
 */
package org.xtext.fLY;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Optimizer Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.fLY.FLYPackage#getOptimizerDeclaration()
 * @model
 * @generated
 */
public interface OptimizerDeclaration extends VariableDeclaration
{
} // OptimizerDeclaration
