/**
 * generated by Xtext 2.16.0
 */
package org.xtext.fLY;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Random Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.fLY.FLYPackage#getRandomDeclaration()
 * @model
 * @generated
 */
public interface RandomDeclaration extends VariableDeclaration
{
} // RandomDeclaration
