/**
 * generated by Xtext 2.16.0
 */
package org.xtext.fLY;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sub Index</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.fLY.SubIndex#getValue <em>Value</em>}</li>
 *   <li>{@link org.xtext.fLY.SubIndex#getValue2 <em>Value2</em>}</li>
 * </ul>
 *
 * @see org.xtext.fLY.FLYPackage#getSubIndex()
 * @model
 * @generated
 */
public interface SubIndex extends EObject
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(ArithmeticExpression)
   * @see org.xtext.fLY.FLYPackage#getSubIndex_Value()
   * @model containment="true"
   * @generated
   */
  ArithmeticExpression getValue();

  /**
   * Sets the value of the '{@link org.xtext.fLY.SubIndex#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(ArithmeticExpression value);

  /**
   * Returns the value of the '<em><b>Value2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value2</em>' containment reference.
   * @see #setValue2(ArithmeticExpression)
   * @see org.xtext.fLY.FLYPackage#getSubIndex_Value2()
   * @model containment="true"
   * @generated
   */
  ArithmeticExpression getValue2();

  /**
   * Sets the value of the '{@link org.xtext.fLY.SubIndex#getValue2 <em>Value2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value2</em>' containment reference.
   * @see #getValue2()
   * @generated
   */
  void setValue2(ArithmeticExpression value);

} // SubIndex
