/**
 * generated by Xtext 2.16.0
 */
package org.xtext.fLY.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.fLY.DatDeclaration;
import org.xtext.fLY.EnvironmentDeclaration;
import org.xtext.fLY.FLYPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Dat Declaration</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.fLY.impl.DatDeclarationImpl#isOnCloud <em>On Cloud</em>}</li>
 *   <li>{@link org.xtext.fLY.impl.DatDeclarationImpl#getEnvironment <em>Environment</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DatDeclarationImpl extends VariableDeclarationImpl implements DatDeclaration
{
  /**
   * The default value of the '{@link #isOnCloud() <em>On Cloud</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isOnCloud()
   * @generated
   * @ordered
   */
  protected static final boolean ON_CLOUD_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isOnCloud() <em>On Cloud</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isOnCloud()
   * @generated
   * @ordered
   */
  protected boolean onCloud = ON_CLOUD_EDEFAULT;

  /**
   * The cached value of the '{@link #getEnvironment() <em>Environment</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnvironment()
   * @generated
   * @ordered
   */
  protected EnvironmentDeclaration environment;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DatDeclarationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FLYPackage.Literals.DAT_DECLARATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isOnCloud()
  {
    return onCloud;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setOnCloud(boolean newOnCloud)
  {
    boolean oldOnCloud = onCloud;
    onCloud = newOnCloud;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FLYPackage.DAT_DECLARATION__ON_CLOUD, oldOnCloud, onCloud));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EnvironmentDeclaration getEnvironment()
  {
    if (environment != null && environment.eIsProxy())
    {
      InternalEObject oldEnvironment = (InternalEObject)environment;
      environment = (EnvironmentDeclaration)eResolveProxy(oldEnvironment);
      if (environment != oldEnvironment)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, FLYPackage.DAT_DECLARATION__ENVIRONMENT, oldEnvironment, environment));
      }
    }
    return environment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EnvironmentDeclaration basicGetEnvironment()
  {
    return environment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEnvironment(EnvironmentDeclaration newEnvironment)
  {
    EnvironmentDeclaration oldEnvironment = environment;
    environment = newEnvironment;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FLYPackage.DAT_DECLARATION__ENVIRONMENT, oldEnvironment, environment));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FLYPackage.DAT_DECLARATION__ON_CLOUD:
        return isOnCloud();
      case FLYPackage.DAT_DECLARATION__ENVIRONMENT:
        if (resolve) return getEnvironment();
        return basicGetEnvironment();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FLYPackage.DAT_DECLARATION__ON_CLOUD:
        setOnCloud((Boolean)newValue);
        return;
      case FLYPackage.DAT_DECLARATION__ENVIRONMENT:
        setEnvironment((EnvironmentDeclaration)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FLYPackage.DAT_DECLARATION__ON_CLOUD:
        setOnCloud(ON_CLOUD_EDEFAULT);
        return;
      case FLYPackage.DAT_DECLARATION__ENVIRONMENT:
        setEnvironment((EnvironmentDeclaration)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FLYPackage.DAT_DECLARATION__ON_CLOUD:
        return onCloud != ON_CLOUD_EDEFAULT;
      case FLYPackage.DAT_DECLARATION__ENVIRONMENT:
        return environment != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (onCloud: ");
    result.append(onCloud);
    result.append(')');
    return result.toString();
  }

} //DatDeclarationImpl
