/**
 * generated by Xtext 2.16.0
 */
package org.xtext.fLY.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.fLY.FLYPackage;
import org.xtext.fLY.ObjectLiteral;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Object Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ObjectLiteralImpl extends ArithmeticExpressionImpl implements ObjectLiteral
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ObjectLiteralImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FLYPackage.Literals.OBJECT_LITERAL;
  }

} //ObjectLiteralImpl
