/**
 * generated by Xtext 2.16.0
 */
package org.xtext.fLY.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.fLY.FLYPackage;
import org.xtext.fLY.OptimizerDeclaration;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Optimizer Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class OptimizerDeclarationImpl extends VariableDeclarationImpl implements OptimizerDeclaration
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OptimizerDeclarationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FLYPackage.Literals.OPTIMIZER_DECLARATION;
  }

} //OptimizerDeclarationImpl
