/**
 * generated by Xtext 2.16.0
 */
package org.xtext.ui.contentassist;

import org.xtext.ui.contentassist.AbstractFLYProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class FLYProposalProvider extends AbstractFLYProposalProvider {
}
