/**
 * generated by Xtext 2.14.0
 */
package org.xtext;

import org.xtext.FLYStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class FLYStandaloneSetup extends FLYStandaloneSetupGenerated {
  public static void doSetup() {
    new FLYStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
