/*
 * generated by Xtext 2.16.0
 */
package org.xtext.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class FLYUiModule extends AbstractFLYUiModule {
}
