/*
 * generated by Xtext 2.15.0
 */
package org.xtext.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.FLY.ui.internal.FLYActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FLYExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(FLYActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		FLYActivator activator = FLYActivator.getInstance();
		return activator != null ? activator.getInjector(FLYActivator.ORG_XTEXT_FLY) : null;
	}

}
