/**
 * generated by Xtext 2.15.0
 */
package org.xtext.fLY;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Arithmetic Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.fLY.FLYPackage#getArithmeticExpression()
 * @model
 * @generated
 */
public interface ArithmeticExpression extends EObject
{
} // ArithmeticExpression
