/**
 * generated by Xtext 2.15.0
 */
package org.xtext.fLY;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sort Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.fLY.SortExpression#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.fLY.SortExpression#getTarget <em>Target</em>}</li>
 *   <li>{@link org.xtext.fLY.SortExpression#getTaget <em>Taget</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.fLY.FLYPackage#getSortExpression()
 * @model
 * @generated
 */
public interface SortExpression extends Expression
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see org.xtext.fLY.FLYPackage#getSortExpression_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link org.xtext.fLY.SortExpression#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Target</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(VariableDeclaration)
   * @see org.xtext.fLY.FLYPackage#getSortExpression_Target()
   * @model
   * @generated
   */
  VariableDeclaration getTarget();

  /**
   * Sets the value of the '{@link org.xtext.fLY.SortExpression#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(VariableDeclaration value);

  /**
   * Returns the value of the '<em><b>Taget</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Taget</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Taget</em>' attribute.
   * @see #setTaget(String)
   * @see org.xtext.fLY.FLYPackage#getSortExpression_Taget()
   * @model
   * @generated
   */
  String getTaget();

  /**
   * Sets the value of the '{@link org.xtext.fLY.SortExpression#getTaget <em>Taget</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Taget</em>' attribute.
   * @see #getTaget()
   * @generated
   */
  void setTaget(String value);

} // SortExpression
