/*
 * generated by Xtext 2.16.0
 */
package org.xtext.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.xtext.fLY.Fly
import org.junit.runner.RunWith
import org.eclipse.xtext.testing.XtextRunner


@ExtendWith(InjectionExtension)
@InjectWith(FLYInjectorProvider)
class FLYParsingTest {
	@Inject
	ParseHelper<Fly> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			for a in [0:10]{
				println a
			}
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
